version: '3.8'

services:
  postgres-userservice:
    image: postgres:15
    container_name: postgres-userservice
    environment:
      POSTGRES_DB: user_service_dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata_userservice:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  pgdata_userservice:

networks:
  user-service-network:
