version: '3.8'

services:
  postgres-userservice:
    image: postgres:15
    container_name: postgres-userservice
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata_userservice:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  pgdata_userservice:

networks:
  user-service-network:
